### ISSUE TITLE
demo app show without any items

### ISSUE THREAD

**Issue by tumpux** [hupptechnologies/shopping-app-with-cart-flutter-demo#1]
![image](https://user-images.githubusercontent.com/21016363/52862868-3dd5d480-3171-11e9-9152-7d73a6ace8fe.png)

any idea why only show blank screen with cart image on the top?

**Comment by hupptechnologies** [comment]
Will check and update it sure.

**Comment by hupptechnologies** [comment]
@tumpux  Please check now.

**Comment by raghav7203** [comment]
I'm having the same issue @hupptechnologies. Please help!
